version: "3.9"

services:
  redis:
    image: redis:7

  db:
    image: postgis/postgis:15-3.3-alpine
    env_file: ".env"
    ports:
      - 5432:5432
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./postgres/postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    command: poetry run uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8080:8000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
    restart: always

  worker:
    build: .
    command: poetry run celery -A app.core.tasks worker --loglevel=info --logfile=app/logging/celery.log
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  dashboard:
    build: .
    command: poetry run celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5557:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - worker
